# Generated by Django 4.2.4 on 2023-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default="you@gmail.com", max_length=50, null=True, unique=True
            ),
        ),
    ]
