# Generated by Django 4.2.4 on 2023-08-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0002_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                default=None, max_length=50, null=True, unique=True
            ),
        ),
    ]
