# Generated by Django 4.2.4 on 2023-09-04 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "service_option",
                    models.CharField(
                        choices=[
                            ("Emergency care", "Emergency care"),
                            ("Operation & Surgery", "Operation & Surgery"),
                            ("Outdoor Checkup", "Outdoor Checkup"),
                            ("Ambulance Service", "Ambulance Service"),
                            ("Medcine & Pharmacy", "Medcine & Pharmacy"),
                            ("Medical Lab", "Medical Lab"),
                            ("General Health", "General Health"),
                            ("Cardiology", "Cardiology"),
                            ("Dental", "Dental"),
                            ("Neurology", "Neurology"),
                            ("Orthopaedics", "Orthopaedics"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "service_logo",
                    models.ImageField(blank=True, null=True, upload_to="service_logo/"),
                ),
                ("price", models.BigIntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "hod",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientMedicalHHistory",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("next_approved_date", models.DateField(blank=True, null=True)),
                ("next_approved_time", models.TimeField(blank=True, null=True)),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "patient_status",
                    models.CharField(
                        choices=[
                            ("unkown", "unkown"),
                            ("Booked for Test", "Booked for Test"),
                            ("Transferred", "Transferred"),
                            ("Admitted", "Admitted"),
                            ("Discharged", "Discharged"),
                            ("Dead", "Dead"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "doctor_remark",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "approved_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approved_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicesApp.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingService",
            fields=[
                ("booking_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("approved_time", models.TimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment", models.BooleanField(blank=True, default=False, null=True)),
                ("served", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "patient_status",
                    models.CharField(
                        choices=[
                            ("unkown", "unkown"),
                            ("Booked for Test", "Booked for Test"),
                            ("Transferred", "Transferred"),
                            ("Admitted", "Admitted"),
                            ("Discharged", "Discharged"),
                            ("Dead", "Dead"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "doctor_remark",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("price", models.BigIntegerField(default=0)),
                (
                    "consultant_doctor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultant_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident_doctor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicesApp.service",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
