# Generated by Django 4.2.4 on 2023-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_option",
            field=models.CharField(
                choices=[
                    ("Emergency care", "Emergency care"),
                    ("Operation & Surgery", "Operation & Surgery"),
                    ("Outdoor Checkup", "Outdoor Checkup"),
                    ("Ambulance Service", "Ambulance Service"),
                    ("Medcine & Pharmacy", "Medcine & Pharmacy"),
                    ("Medical Lab", "Medical Lab"),
                    ("General Health", "General Health"),
                    ("Cardiology", "Cardiology"),
                    ("Dental", "Dental"),
                    ("Neurology", "Neurology"),
                    ("Orthopaedics", "Orthopaedics"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
